@Consilium = http://localhost:5202
@email = bob@example.com
@key = Nwx0P84B2GW0l992eFP8

###
GET {{Consilium}}/todo
Email-Auth_Email: {{email}}
Email-Auth_ApiKey: {{key}}
###
POST {{Consilium}}/todo
Email-Auth_Email: {{email}}
Email-Auth_ApiKey: {{key}}
Content-Type: application/json
  {
    "title": "Addition",
    "description": null,
    "category": "School",
    "isCompleted": false
  }
###
PATCH {{Consilium}}/todo/update
Email-Auth_Email: {{email}}
Email-Auth_ApiKey: {{key}}
Content-Type: application/json
  {
    "id": 2,
    "isCompleted": false
  }
###
DELETE {{Consilium}}/todo/remove/2
Email-Auth_Email: {{email}}
Email-Auth_ApiKey: {{key}}


